apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deploy
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kpryu6/argocd-test.git 
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

